<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Target .NET 6 to align with the API project -->
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
  </ItemGroup>

</Project>